# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from icd.v1 import icd_pb2 as icd_dot_v1_dot_icd__pb2


class TalosOperatorServiceStub(object):
    """The historical transport exposed a command wrapper with message and command
    identifiers. gRPC already correlates each request/response pair based on the
    RPC method and stream, so the explicit MessageId/CommandId fields are no
    longer required and have been omitted here.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/icd.v1.TalosOperatorService/Handshake',
                request_serializer=icd_dot_v1_dot_icd__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.PolarPanDiscrete = channel.unary_unary(
                '/icd.v1.TalosOperatorService/PolarPanDiscrete',
                request_serializer=icd_dot_v1_dot_icd__pb2.PolarPanDiscreteRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.PolarPanDiscreteResponse.FromString,
                _registered_method=True)
        self.Home = channel.unary_unary(
                '/icd.v1.TalosOperatorService/Home',
                request_serializer=icd_dot_v1_dot_icd__pb2.HomeRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.HomeResponse.FromString,
                _registered_method=True)
        self.PolarPanContinuousStart = channel.unary_unary(
                '/icd.v1.TalosOperatorService/PolarPanContinuousStart',
                request_serializer=icd_dot_v1_dot_icd__pb2.PolarPanContinuousStartRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.PolarPanContinuousStartResponse.FromString,
                _registered_method=True)
        self.PolarPanContinuousStop = channel.unary_unary(
                '/icd.v1.TalosOperatorService/PolarPanContinuousStop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.PolarPanContinuousStopResponse.FromString,
                _registered_method=True)
        self.CartesianMoveDiscrete = channel.unary_unary(
                '/icd.v1.TalosOperatorService/CartesianMoveDiscrete',
                request_serializer=icd_dot_v1_dot_icd__pb2.CartesianMoveDiscreteRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.CartesianMoveDiscreteResponse.FromString,
                _registered_method=True)
        self.CartesianMoveContinuousStart = channel.unary_unary(
                '/icd.v1.TalosOperatorService/CartesianMoveContinuousStart',
                request_serializer=icd_dot_v1_dot_icd__pb2.CartesianMoveContinuousStartRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.CartesianMoveContinuousStartResponse.FromString,
                _registered_method=True)
        self.CartesianMoveContinuousStop = channel.unary_unary(
                '/icd.v1.TalosOperatorService/CartesianMoveContinuousStop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.CartesianMoveContinuousStopResponse.FromString,
                _registered_method=True)
        self.ExecuteHardwareOperation = channel.unary_unary(
                '/icd.v1.TalosOperatorService/ExecuteHardwareOperation',
                request_serializer=icd_dot_v1_dot_icd__pb2.ExecuteHardwareOperationRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.ExecuteHardwareOperationResponse.FromString,
                _registered_method=True)
        self.GetSpeed = channel.unary_unary(
                '/icd.v1.TalosOperatorService/GetSpeed',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.GetSpeedResponse.FromString,
                _registered_method=True)
        self.SetSpeed = channel.unary_unary(
                '/icd.v1.TalosOperatorService/SetSpeed',
                request_serializer=icd_dot_v1_dot_icd__pb2.SetSpeedRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.SetSpeedResponse.FromString,
                _registered_method=True)
        self.SavePosition = channel.unary_unary(
                '/icd.v1.TalosOperatorService/SavePosition',
                request_serializer=icd_dot_v1_dot_icd__pb2.SavePositionRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.SavePositionResponse.FromString,
                _registered_method=True)
        self.DeletePosition = channel.unary_unary(
                '/icd.v1.TalosOperatorService/DeletePosition',
                request_serializer=icd_dot_v1_dot_icd__pb2.DeletePositionRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.DeletePositionResponse.FromString,
                _registered_method=True)
        self.GoToPosition = channel.unary_unary(
                '/icd.v1.TalosOperatorService/GoToPosition',
                request_serializer=icd_dot_v1_dot_icd__pb2.GoToPositionRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.GoToPositionResponse.FromString,
                _registered_method=True)
        self.SetPolarPosition = channel.unary_unary(
                '/icd.v1.TalosOperatorService/SetPolarPosition',
                request_serializer=icd_dot_v1_dot_icd__pb2.SetPolarPositionRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.SetPolarPositionResponse.FromString,
                _registered_method=True)
        self.GetPolarPosition = channel.unary_unary(
                '/icd.v1.TalosOperatorService/GetPolarPosition',
                request_serializer=icd_dot_v1_dot_icd__pb2.GetPolarPositionRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.GetPolarPositionResponse.FromString,
                _registered_method=True)
        self.SetCartesianPosition = channel.unary_unary(
                '/icd.v1.TalosOperatorService/SetCartesianPosition',
                request_serializer=icd_dot_v1_dot_icd__pb2.SetCartesianPositionRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.SetCartesianPositionResponse.FromString,
                _registered_method=True)
        self.GetCartesianPosition = channel.unary_unary(
                '/icd.v1.TalosOperatorService/GetCartesianPosition',
                request_serializer=icd_dot_v1_dot_icd__pb2.GetCartesianPositionRequest.SerializeToString,
                response_deserializer=icd_dot_v1_dot_icd__pb2.GetCartesianPositionResponse.FromString,
                _registered_method=True)


class TalosOperatorServiceServicer(object):
    """The historical transport exposed a command wrapper with message and command
    identifiers. gRPC already correlates each request/response pair based on the
    RPC method and stream, so the explicit MessageId/CommandId fields are no
    longer required and have been omitted here.

    """

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PolarPanDiscrete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Home(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PolarPanContinuousStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PolarPanContinuousStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CartesianMoveDiscrete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CartesianMoveContinuousStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CartesianMoveContinuousStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteHardwareOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SavePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GoToPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPolarPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolarPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCartesianPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCartesianPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TalosOperatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.HandshakeRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.HandshakeResponse.SerializeToString,
            ),
            'PolarPanDiscrete': grpc.unary_unary_rpc_method_handler(
                    servicer.PolarPanDiscrete,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.PolarPanDiscreteRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.PolarPanDiscreteResponse.SerializeToString,
            ),
            'Home': grpc.unary_unary_rpc_method_handler(
                    servicer.Home,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.HomeRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.HomeResponse.SerializeToString,
            ),
            'PolarPanContinuousStart': grpc.unary_unary_rpc_method_handler(
                    servicer.PolarPanContinuousStart,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.PolarPanContinuousStartRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.PolarPanContinuousStartResponse.SerializeToString,
            ),
            'PolarPanContinuousStop': grpc.unary_unary_rpc_method_handler(
                    servicer.PolarPanContinuousStop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.PolarPanContinuousStopResponse.SerializeToString,
            ),
            'CartesianMoveDiscrete': grpc.unary_unary_rpc_method_handler(
                    servicer.CartesianMoveDiscrete,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.CartesianMoveDiscreteRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.CartesianMoveDiscreteResponse.SerializeToString,
            ),
            'CartesianMoveContinuousStart': grpc.unary_unary_rpc_method_handler(
                    servicer.CartesianMoveContinuousStart,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.CartesianMoveContinuousStartRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.CartesianMoveContinuousStartResponse.SerializeToString,
            ),
            'CartesianMoveContinuousStop': grpc.unary_unary_rpc_method_handler(
                    servicer.CartesianMoveContinuousStop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.CartesianMoveContinuousStopResponse.SerializeToString,
            ),
            'ExecuteHardwareOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteHardwareOperation,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.ExecuteHardwareOperationRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.ExecuteHardwareOperationResponse.SerializeToString,
            ),
            'GetSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpeed,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.GetSpeedResponse.SerializeToString,
            ),
            'SetSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpeed,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.SetSpeedRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.SetSpeedResponse.SerializeToString,
            ),
            'SavePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SavePosition,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.SavePositionRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.SavePositionResponse.SerializeToString,
            ),
            'DeletePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePosition,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.DeletePositionRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.DeletePositionResponse.SerializeToString,
            ),
            'GoToPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GoToPosition,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.GoToPositionRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.GoToPositionResponse.SerializeToString,
            ),
            'SetPolarPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPolarPosition,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.SetPolarPositionRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.SetPolarPositionResponse.SerializeToString,
            ),
            'GetPolarPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolarPosition,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.GetPolarPositionRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.GetPolarPositionResponse.SerializeToString,
            ),
            'SetCartesianPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCartesianPosition,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.SetCartesianPositionRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.SetCartesianPositionResponse.SerializeToString,
            ),
            'GetCartesianPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCartesianPosition,
                    request_deserializer=icd_dot_v1_dot_icd__pb2.GetCartesianPositionRequest.FromString,
                    response_serializer=icd_dot_v1_dot_icd__pb2.GetCartesianPositionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'icd.v1.TalosOperatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('icd.v1.TalosOperatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TalosOperatorService(object):
    """The historical transport exposed a command wrapper with message and command
    identifiers. gRPC already correlates each request/response pair based on the
    RPC method and stream, so the explicit MessageId/CommandId fields are no
    longer required and have been omitted here.

    """

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/Handshake',
            icd_dot_v1_dot_icd__pb2.HandshakeRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PolarPanDiscrete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/PolarPanDiscrete',
            icd_dot_v1_dot_icd__pb2.PolarPanDiscreteRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.PolarPanDiscreteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Home(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/Home',
            icd_dot_v1_dot_icd__pb2.HomeRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.HomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PolarPanContinuousStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/PolarPanContinuousStart',
            icd_dot_v1_dot_icd__pb2.PolarPanContinuousStartRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.PolarPanContinuousStartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PolarPanContinuousStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/PolarPanContinuousStop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            icd_dot_v1_dot_icd__pb2.PolarPanContinuousStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CartesianMoveDiscrete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/CartesianMoveDiscrete',
            icd_dot_v1_dot_icd__pb2.CartesianMoveDiscreteRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.CartesianMoveDiscreteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CartesianMoveContinuousStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/CartesianMoveContinuousStart',
            icd_dot_v1_dot_icd__pb2.CartesianMoveContinuousStartRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.CartesianMoveContinuousStartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CartesianMoveContinuousStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/CartesianMoveContinuousStop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            icd_dot_v1_dot_icd__pb2.CartesianMoveContinuousStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteHardwareOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/ExecuteHardwareOperation',
            icd_dot_v1_dot_icd__pb2.ExecuteHardwareOperationRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.ExecuteHardwareOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/GetSpeed',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            icd_dot_v1_dot_icd__pb2.GetSpeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/SetSpeed',
            icd_dot_v1_dot_icd__pb2.SetSpeedRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.SetSpeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SavePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/SavePosition',
            icd_dot_v1_dot_icd__pb2.SavePositionRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.SavePositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/DeletePosition',
            icd_dot_v1_dot_icd__pb2.DeletePositionRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.DeletePositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GoToPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/GoToPosition',
            icd_dot_v1_dot_icd__pb2.GoToPositionRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.GoToPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPolarPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/SetPolarPosition',
            icd_dot_v1_dot_icd__pb2.SetPolarPositionRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.SetPolarPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolarPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/GetPolarPosition',
            icd_dot_v1_dot_icd__pb2.GetPolarPositionRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.GetPolarPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCartesianPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/SetCartesianPosition',
            icd_dot_v1_dot_icd__pb2.SetCartesianPositionRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.SetCartesianPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCartesianPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/icd.v1.TalosOperatorService/GetCartesianPosition',
            icd_dot_v1_dot_icd__pb2.GetCartesianPositionRequest.SerializeToString,
            icd_dot_v1_dot_icd__pb2.GetCartesianPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
